config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    get '/about', to: 'static_pages#about'
    get '/contact', to: 'static_pages#contact'
    get '/register', to: 'users#new'
    post '/register', to: 'users#create'
    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    # vars
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # model
    before_save { email.downcase! }
    validates :name,  presence: true, length: {maximum: 50}
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
    has_secure_password
    # Returns the hash digest of the given string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    # Returns a random token
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    class << self
        # Returns the has digest of a given string
        def digest(string)
            cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
            BCrypt::Password.create(string, cost: cost)
        end
        # Returns a random token
        def new_token
            SecureRandom.urlsafe_base64
        end
    end
    # Persistent sessions
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    # Returns true if the given token matches the digest
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    # Forget a user
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          signin user
          params[:session][:remember_me] == '1' ? remember(user) : forget(user)
          remember user
          redirect_to user
      else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
      end
  end
  def destroy
      log_out if signed_in?
      redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def about
  end
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
        # The debugger console can be used when uncommenting the helper below
        # debugger
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            signin @user
            flash[:success] = "Congrats. You're now our eternal slave."
            redirect_to @user
        else
            render 'new'
        end
    end
    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "The Brief"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def signin(user)
        session[:user_id] = user.id
    end
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    # Returns the user corresponding to the remember token cookie
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                signin user
                @current_user = user
            end
        end
    end
    def signed_in?
        !current_user.nil?
    end
    # Forget a persistent session
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="page-alerts">
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
    <div class="container">
        <p>Ryan S. Rich - &copy; 2016</p>
        <nav>
            <% if signed_in? %>
                <%= link_to "About", about_path %>
                <%= link_to "Blog", "#" %>
                <%= link_to "Contact", contact_path %>
                <%= link_to "Profile", current_user %>
                <%= link_to "Log out", logout_path, method: "delete" %>
            <% else %>
                <%= link_to "About", about_path %>
                <%= link_to "Register", register_path %>
                <%= link_to "Sign in", signin_path %>
            <% end %>
        </nav>
    </div>
</footer>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= render 'layouts/shim' %>

app/views/layouts/_header.html.erb
<header class="main-header">
    <div class="container">
        <%= link_to "The Brief", "/", id: "logo" %>
        <nav>
            <% if signed_in? %>
                <%= link_to "Help", about_path %>
                <%= link_to "Briefs", '#' %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Settings", '#' %></li>
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    </ul>
                </li>
            <% else %>
                <%= link_to "About", about_path %>
                <%= link_to "Help", about_path %>
                <%= link_to "Blog", "#" %>
                <%= link_to "Contact", contact_path %>
                <%= link_to "Register", register_path, class: "button-alt" %>
                <%= link_to "Sign in", signin_path , class: "button" %>
            <% end %>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script> <![endif]-->

app/views/layouts/application.html.erb
<!-- Design Brief Application -->
<!DOCTYPE html>
<html>
    <head>
        <%= render 'layouts/head' %>
    </head>
    <body>
        <%= render 'layouts/flash' %>
        <%= render 'layouts/header' %>
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">Sorry about that. It seems the form contained <%= pluralize(@user.errors.count, "error")%>. Please see the details below &darr;</div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg%></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<section class="masthead">
    <div class="container">
        <h1>About The Brief</h1>
        <article>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Nulla vitae elit libero, a pharetra augue. Etiam porta sem malesuada magna mollis euismod. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
            <p>Sed posuere consectetur est at lobortis. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
        </article>
    </div>
</section>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<section class="masthead">
    <div class="container">
        <h1>Contact</h1>
        <a href="mailto:ryan@catalyze.io" class="button">ryan@catalyze.io</a>
    </div>
</section>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<section class="masthead">
    <div class="container">
        <h1>Hello</h1>
        <%= link_to "Sign up!", register_path, class: "button" %>
    </div>
</section>

app/views/users/new.html.erb
<% provide(:title, "Register for an account") %>
<section class="signup">
    <div class="container">
        <h1>Register</h1>
        <%= form_for(@user, url: register_path) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            <%= f.submit "Create my account", class: "button-submit" %>
        <% end %>
    </div>
</section>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<section class="profile">
    <div class="container">
        <div class="grav"><%= gravatar_for @user %></div>
        <h1><%= @user.name %></h1>
    </div>
    <div class="container">
        <div class="meta">
            <p><em>Join Date:</em> <%= @user.created_at.strftime("%Y") %></p>
            <p><em>Email:</em> <%= @user.email %></p>
        </div>
    </div>
</section>